traducción debugging.md y issue #302
flutter-es/website pull request #317
Opened 2018-09-08 20:22 UTC by Twinber

close #40 
close #302

2018-09-09 21:35 UTC, Arkangel12 requested changes
buena lectura! pocos cambios! 👍

2018-09-09 21:35 UTC, Arkangel12 commented on es_ES/debugging.md
> +y te ayuda a encontrar posibles errores. Si esás usando un [IDE/editor que soporte Flutter](/get-started/editor/),
estás usando..

2018-09-09 21:35 UTC, Arkangel12 commented on es_ES/debugging.md
> +usa pra reducir cuanto necesita ser repintando.
para

2018-09-09 21:35 UTC, Arkangel12 commented on es_ES/debugging.md
> +Puedes tambien obtner un volcado del árbol de Semántica (el árbol
obtener

2018-09-09 21:35 UTC, Arkangel12 commented on es_ES/debugging.md
> +para impirmir el principio y el final de los frames a la consola.
imprimir

2018-09-09 21:35 UTC, Arkangel12 commented on es_ES/debugging.md
> +sea true. La manera más sencilla de fijar esto es al principio de tu punto
marca true de alguna forma ya sea **true** o _true_ pero que se vea que es la propiedad o bien que sea traducido a **verdadero**

2018-09-09 21:35 UTC, Arkangel12 commented on es_ES/debugging.md
> +con una caja de un azul más oscuro alrededor del hijo, alieciones
alineaciones

2018-09-09 21:35 UTC, Arkangel12 commented on es_ES/debugging.md
> +en el framerowk Flutter que empiza con "`debug...`" solo funciona en modo
framework

2018-09-09 21:35 UTC, Arkangel12 commented on es_ES/debugging.md
> +Para obtener una representación gráfica del renidmiento de tu aplicación, fija
rendimiento

2018-09-09 21:35 UTC, Arkangel12 commented on es_ES/debugging.md
> +sobre la aplicación para ayudar a verificar alineciones. Para este fin, el
alineaciones

2018-09-09 21:35 UTC, Arkangel12 commented on es_ES/debugging.md
> +debug , se superpone un grid.
eliminar espacio despues de `debug`

2018-09-09 21:35 UTC, Arkangel12 commented on es_ES/debugging.md
> +El limite de ficheros que se pueden tener abiertos por defecto para Mac OS es
MacOS

2018-09-10 19:43 UTC, drnodev requested changes

2018-09-10 19:43 UTC, alexcotte commented on es_ES/layout.md
>  Flex
máximos para el ancho y alto;
varían de tipo en tipo

2018-09-10 19:43 UTC, alexcotte commented on es_ES/flutter-for-react-native/index.md
> +[AboutDialog](https://docs.flutter.io/flutter/material/AboutDialog-class.html), [CircleAvatar](https://docs.flutter.io/flutter/material/CircleAvatar-class.html), y [Text](https://docs.flutter.io/flut
ontiene archivos de origen Dart  -> contiene archivos de origen Dart

2018-09-10 19:43 UTC, alexcotte commented on es_ES/flutter-for-react-native/index.md
> +[AboutDialog](https://docs.flutter.io/flutter/material/AboutDialog-class.html), [CircleAvatar](https://docs.flutter.io/flutter/material/CircleAvatar-class.html), y [Text](https://docs.flutter.io/flut
de estilo y y luego -->  de estilo y luego

2018-09-11 22:02 UTC, Arkangel12 approved these changes
🚀  estaba corto este! 😄  bueno su revision 😂

2018-09-12 18:21 UTC, drnodev approved these changes

2018-09-12 18:24 UTC, merged