Update index.html
flutter-es/website pull request #460
Opened 2019-03-02 16:17 UTC by NicolasERT

2019-03-02 16:30 UTC, NicolasERT commented
close #440

2019-03-03 20:48 UTC, caveligh commented on src_es/create/index.html
> +            Ya sea un principiante o un experto en Flutter, lo invitamos a unirse a
Tanto si eres un principiante como un experto con Flutter, te invitamos a que te unas a nosotros y veas lo que puedes crear

2019-03-03 20:49 UTC, caveligh commented on src_es/create/index.html
> -            <i class="fab fa-twitter fa-lg"></i>&nbsp;&nbsp;&nbsp;Share #FlutterCreate with your friends
Comparte #Flutter-Create con tus amigos

2019-03-03 20:50 UTC, caveligh commented on src_es/create/index.html
> -        <h6>What to make:</h6>
¿Qué hacer?

2019-03-03 20:52 UTC, caveligh commented on src_es/create/index.html
> -          less of Dart&nbsp;code</h2> <a class="create__cta btn btn-primary mb-8" href="https://docs.google.com/forms/d/1YrsnBlMFenKDrmGlcaPbKTbxbdWsua8_TMExoRwgyv4">Submit your app</a>
Crea una nueva experiencia con Flutter de 5KB o menos de código Dart

2019-03-03 20:53 UTC, caveligh commented on src_es/create/index.html
> +        <h2 class="mt-0">Cree una experiencia novedosa con Flutter en 5KB o
Crea una nueva experiencia con Flutter de 5KB o menos de código Dart

2019-03-03 20:56 UTC, caveligh commented on src_es/create/index.html
> +        <p>Las entradas serán evauadas por un pane de expertos de futter según os siguientes cuatro criterios:</p>
Los trabajos serán evaluados por un panel de expertos de Flutter con base en los siguientes cuatro criterios:

2019-03-03 20:59 UTC, caveligh commented on src_es/create/index.html
> +            <div class="col-12 mt-8">Además, todas las presentaciones recibirán un certificado digital de finalización.
Además, todos los trabajos presentados recibirán un certificado digital de finalización.

2019-03-03 21:00 UTC, caveligh commented on src_es/create/index.html
> +        <h4>Pautas para el envío:</h4>
Directrices para la presentación de propuestas:

2019-03-03 21:03 UTC, caveligh commented on src_es/create/index.html
> +            <p>Su solicitud debe enviarse en forma de un archivo ZIP que contenga
Tu solicitud debe enviarse en forma de archivo ZIP que contenga todo lo necesario para ejecutarla en un dispositivo Android o iOS de destino.

2019-03-03 21:04 UTC, caveligh commented on src_es/create/index.html
> +            <p>Debe incluir un archivo <code>README.md</code> que incluya una breve
Debes

2019-03-03 21:04 UTC, caveligh commented on src_es/create/index.html
> +                plataforma específica objetivo).</p>
plataforma objetivo específica

2019-03-03 21:05 UTC, caveligh commented on src_es/create/index.html
> +                beneficiarse de su trabajo.</p>
tu trabajo

2019-03-03 21:06 UTC, caveligh commented on src_es/create/index.html
> +            <p>Ejecutaremos la aplicación desempaquetando el archivo ZIP y corriendo
y ejecutando

2019-03-03 21:12 UTC, caveligh commented on src_es/create/index.html
> +            <p>El código Dart debe ser contenido en un archivo cuyo nombre de archivo
El código de Dart debe aparecer en un archivo que tenga un nombre de archivo que termine en .dart

2019-03-03 21:17 UTC, caveligh commented on src_es/create/index.html
> +                más de 5,120 bytes medido (por ejemplo) por el comando
superior a 5,120 bytes medidos como (por ejemplo) por el comando

2019-03-03 21:22 UTC, caveligh commented on src_es/create/index.html
> +            <p>Las inscripciones no pueden ser enviadas por ninguna persona menor de edad en el momento de la
Los trabajos no podrán ser presentados por ninguna persona que sea menor de edad en el momento de la inscripción.

2019-03-03 21:23 UTC, caveligh commented on src_es/create/index.html
> +            <p>Las personas de los siguientes países o regiones pueden presentar, pero no se considerarán elegibles para
Las personas de los siguientes países o regiones pueden participar, pero no serán consideradas elegibles para el concurso debido a las reglas locales, incluyendo la exclusión del jurado y de los premios: Italia, Brasil, Quebec y México.

2019-03-03 21:24 UTC, caveligh commented on src_es/create/index.html
> +            <p>Las presentaciones de los siguientes países embargados no se considerarám elegibles para el concurso,
Los trabajos de los siguientes países sujetos a embargo no serán considerados elegibles para el concurso, incluyendo la exclusión del jurado y de los premios: Crimea, Cuba, Irán, Siria, Corea del Norte y Sudán.

2019-03-03 21:27 UTC, caveligh commented on src_es/create/index.html
> +                o de lo contrario no cumple con el tema y espíritu del concurso.</p>
o que de alguna otra manera no cumpla con el tema y el espíritu del concurso.

2019-03-03 21:27 UTC, caveligh commented on src_es/create/index.html
> +            <p>TNo deben contener ningún contenido, material o cualquier elemento que sea ilegal, o que infrinja o sea
No deben

2019-03-03 21:28 UTC, caveligh commented on src_es/create/index.html
> +                contrario a toas las leyes y regulaciones federakes, estatales o locales aplicables, incluidas las leyes
federales

2019-03-03 21:29 UTC, caveligh commented on src_es/create/index.html
> +                o regulaciones de cualquier estado donde se creen el garabato y la declaración de respaldo.
donde se hayan creado el garabato y la declaración de apoyo.

2019-03-03 21:31 UTC, caveligh commented on src_es/create/index.html
> +                comercial, representación de personajes de terceros que indiquen un patrocinio o respaldo por parte de
marca registrada

2019-03-03 21:32 UTC, caveligh commented on src_es/create/index.html
> +            <p>Deben ser trabajos originales, no pulicados, que no contengan, incorporen o utilicen ningún contenido,
Deben ser obras originales e inéditas que no contengan,

2019-03-03 21:36 UTC, caveligh commented on src_es/create/index.html
> +            <p>No pueden contener ningún contenido, elemento o material que viole los derechos de publicidad, privacidad
No pueden incluir

2019-03-03 21:36 UTC, caveligh commented on src_es/create/index.html
> +            <p>La presentación no es objeto de ningún litigio o reclamo real o amenazado</p>
real o potencial.

2019-03-03 21:37 UTC, caveligh commented on src_es/create/index.html
> +            <p>El participante no incluye comentarios despectivos relacionados con el Patrocinador o un tercero.</p>
El participante no incluye ningún comentario despectivo relacionado con el Patrocinador o un tercero.

2019-03-03 21:40 UTC, caveligh commented on src_es/create/index.html
> +                proyecto creado utilizando Flutter. Es una forma divertida de aprender Flutter, itente construir
un proyecto construido

2019-03-03 21:41 UTC, caveligh commented on src_es/create/index.html
> +                <b>¿Cuál es el criterio a juzgar? </b><br>
¿Cuáles son los criterios de evaluación?

2019-03-03 21:44 UTC, caveligh commented on src_es/create/index.html
> +                Las entradas serán evaluadas por miembros del equipo de Flutter y desarrolladores experimentados de la
Los trabajos serán evaluados

2019-03-03 21:46 UTC, caveligh commented on src_es/create/index.html
> +                Los jueces evaluarán las entradas según cuatro criterios: belleza visual, calidad del código, novedad de
evaluarán los trabajos

2019-03-03 21:48 UTC, caveligh commented on src_es/create/index.html
> +                <b>¿Puedo enviar más de una entrada?</b><br>
más de un trabajo

2019-03-03 21:49 UTC, caveligh commented on src_es/create/index.html
> +                Limitamos las entradas a un proyecto por participante. ¡Te animamos a enviar tu mejor entrada!
Limitamos las inscripciones

2019-03-03 21:52 UTC, caveligh commented on src_es/create/index.html
>              </p>
Nota para Daniel: En esta sección, en la página oficial aparecen 7 preguntas nuevas

2019-03-03 21:54 UTC, caveligh commented on src_es/create/index.html
> +        <h2 class="mt-0">Cree una experiencia de usuario novedosa con Flutter usando 5KB o menos de código&nbsp;Dart
Crea una nueva experiencia de usuario

2019-03-03 21:55 UTC, caveligh requested changes
Hace falta tutear en general durante todo el documento.
Hay una sección que está en la página oficial, pero no aparece acá.

2019-03-03 23:05 UTC, NicolasERT commented on src_es/create/index.html
> -            <i class="fab fa-twitter fa-lg"></i>&nbsp;&nbsp;&nbsp;Share #FlutterCreate with your friends
Esta parte esta traducida correctamente

2019-03-03 23:20 UTC, NicolasERT commented on src_es/create/index.html
>              </p>
Correcto, pero supongo que se actualizará más tarde

2019-03-04 00:11 UTC, caveligh commented on src_es/create/index.html
> +                el concurso debido a las reglas locales, incluyendo la excusión del juerado y de los premios: Italia,
incluyendo la exclusión del jurado y

2019-03-04 00:11 UTC, caveligh commented on src_es/create/index.html
> +                incluiyendo la exclusión del jueces y de los premios: Crimea, Cuba, Irán, Siria, Corea del Norte y
incluyendo

2019-03-04 00:12 UTC, caveligh commented on src_es/create/index.html
> +                contrario a toas las leyes y regulaciones federales, estatales o locales aplicables, incluidas las leyes
todas las leyes

2019-03-04 00:14 UTC, caveligh commented on src_es/create/index.html
> +                proyecto construido utilizando Flutter. Es una forma divertida de aprender Flutter, itente construir
intenta construir

2019-03-04 00:15 UTC, caveligh commented on src_es/create/index.html
> +                Debe enviar su proyecto antes del 7 de abril a las 11:59 pm PDT (GMT-7).
Debes enviar tu

2019-03-04 00:15 UTC, caveligh commented on src_es/create/index.html
> +                Sí, siempre que su cambio ocurra antes del 7 de abril a las 11:59 pm PDT (GMT-7).
Sí, siempre que tu cambio

2019-03-04 00:16 UTC, caveligh requested changes
Hace falta tutear en general durante todo el documento.
Hay una sección que está en la página oficial, pero no aparece acá.

2019-03-04 18:18 UTC, Arkangel12 commented on src_es/create/index.html
> +            nosotros y veas que puedes crear. ¡También tenemos más de $10,000 en premios
$10,000 USD

2019-03-04 18:20 UTC, Arkangel12 commented on src_es/create/index.html
> +                <h3>Apple iMac Pro competamente cargado</h3>
completamente...

2019-03-04 18:25 UTC, Arkangel12 commented on src_es/create/index.html
> +                <code>find . -name "*.dart" | xargs cat | wc -c.</code></p>
el punto al final de esta linea crea un poco de confusión si alguien copiando se lo lleva, marca error en terminal yo se lo quitaría o cambia el mensaje a:

....medido (como por ejemplo) con <code>find . -name "*.dart" | xargs cat | wc -c.</code> ejecutandolo desde terminal en la raíz de tu proyecto.      

creo que es mas descriptivo por algunas preguntas que han surgido en el grupo

2019-03-04 18:29 UTC, Arkangel12 requested changes
algunos comentarios y un par de correcciones.

2019-03-04 18:58 UTC, caveligh approved these changes

2019-03-04 22:24 UTC, Arkangel12 approved these changes
🚀

2019-03-04 22:24 UTC, Arkangel12 commented
una menos!

2019-03-04 22:24 UTC, merged