Close #458
flutter-es/website pull request #463
Opened 2019-03-03 13:43 UTC by Arkangel12

2019-03-03 23:42 UTC, NicolasERT requested changes

2019-03-03 23:42 UTC, NicolasERT commented on src_es/docs/codelabs/index.md
> +Crea una app sencilla que genera nombres propustos para una compañia
nombres propuestos para

2019-03-03 23:42 UTC, NicolasERT commented on src_es/docs/codelabs/index.md
> +startup. En la primera parte, utilizaras un paquete que regresa pares de palabras
la primera parte, utilizarás un

2019-03-03 23:42 UTC, NicolasERT commented on src_es/docs/codelabs/index.md
> +aleatorios y las agregaras a una lista de scroll infinito.
y las agregarás

2019-03-03 23:42 UTC, NicolasERT commented on src_es/docs/codelabs/index.md
> +Crea una app sencilla que genera nombres propustos para una compañia
propuestos

2019-03-03 23:42 UTC, NicolasERT commented on src_es/docs/codelabs/index.md
> +startup. En la segunda parte, extenderá el ejemplo desde la primera parte para permitir
En la segunda parte, extenderás el ejemplo de la primera parte

2019-03-03 23:42 UTC, NicolasERT commented on src_es/docs/codelabs/index.md
> +Una "primera incursión" más profunda que "WEscribe tu primera app en Flutter." En este codelab
que "Escribe tu primera

2019-03-03 23:42 UTC, NicolasERT commented on src_es/docs/codelabs/index.md
> +crearás una aplicación de chat que incluye una simple animación y personalizar
una simple animación y personalizarás

2019-03-03 23:42 UTC, NicolasERT commented on src_es/docs/codelabs/index.md
> +Aprenda los conceptos básicos del uso de _Material Components_ por medio de la construcción
Aprende los conceptos

2019-03-03 23:42 UTC, NicolasERT commented on src_es/docs/codelabs/index.md
> +Aprenda a utilizar Material para la estructura y el diseño en Flutter.
Aprende a utilizar

2019-03-03 23:42 UTC, NicolasERT commented on src_es/docs/codelabs/index.md
> +// Ahora, solo existe una solo lab Java -> Dart , el cual tambien esta
un solo lab... el cual también está

2019-03-03 23:42 UTC, NicolasERT commented on src_es/docs/codelabs/index.md
> +Para codelabs especificos de Dart, ve la pagina
ve a la página

2019-03-04 01:32 UTC, Arkangel12 commented
Cambios de revisión atendidos en espera de existir futuros cambios.

2019-03-04 06:05 UTC, Twinber approved these changes

2019-03-04 06:05 UTC, merged