Navigation named routes.md
flutter-es/website pull request #499
Opened 2019-03-14 13:42 UTC by Twinber

2019-03-16 20:13 UTC, caveligh commented on src_es/docs/cookbook/navigation/navigate-with-arguments.md
> +proporciona la habilidad de navegar a una nombre con nombre desde cualquier parte de la app usando
de navegar a una ruta con nombre

2019-03-16 20:21 UTC, caveligh commented on src_es/docs/cookbook/navigation/navigate-with-arguments.md
> +`ExtractArgumentsScreen` extrae `title` y `message` de estis
de estos

2019-03-16 20:25 UTC, caveligh commented on src_es/docs/cookbook/navigation/navigate-with-arguments.md
> +  // identificar la ruta con nombre que ha sido añadida, con push, y crea la
añadida con push

2019-03-16 20:25 UTC, caveligh commented on src_es/docs/cookbook/navigation/navigate-with-arguments.md
> +    // Si haces push del nombre de la ruta de la pantala PassArgumentsScreen
ruta de la pantalla

2019-03-16 20:28 UTC, caveligh commented on src_es/docs/cookbook/navigation/navigate-with-arguments.md
> +      // identificar la ruta con nombre que ha sido añadida, con push, y crea la
que ha sido añadida con push,

2019-03-16 20:29 UTC, caveligh commented on src_es/docs/cookbook/navigation/navigate-with-arguments.md
> +        // Si haces push del nombre de la ruta de la pantala PassArgumentsScreen
push en el nombre de la ruta de la pantalla

2019-03-16 20:30 UTC, caveligh commented on src_es/docs/cookbook/navigation/navigate-with-arguments.md
> +                 // Cuando el usuario pulsa el botón, navega a una ruta específica
Alinear con línea 226 (preciera que tiene un espacio antes de //)

2019-03-16 20:30 UTC, caveligh commented on src_es/docs/cookbook/navigation/navigate-with-arguments.md
> +                // y proporciona los argumentos como pate de RouteSettings.
y proporciona los argumentos como parte de

2019-03-16 20:34 UTC, caveligh requested changes
Pocos cambios. 
El archivo src/docs/cookbook/navigation/navigate-with-arguments.md está todo en inglés, supongo que es una actualización con respecto a master.

2019-03-18 17:46 UTC, Arkangel12 requested changes
pocos detalles! 😄

2019-03-18 17:46 UTC, Arkangel12 commented on src_es/docs/cookbook/navigation/navigate-with-arguments.md
> +## Complete example
Ejemplo completo

2019-03-18 17:46 UTC, Arkangel12 commented on src_es/docs/cookbook/navigation/navigate-with-arguments.md
> +      // Covierte los argumentos al tipo correcto: ScreenArguments.
Convierte

2019-03-18 17:46 UTC, Arkangel12 commented on src_es/docs/cookbook/navigation/navigate-with-arguments.md
> +  // Los agumentos son extraidos por la función onGenerateRoute proporcionada por el
argumentos

2019-03-22 18:53 UTC, Arkangel12 approved these changes
🚀

2019-03-22 20:40 UTC, caveligh approved these changes

2019-03-23 16:50 UTC, merged